export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    age: 25,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Engineer",
    hobby: "Playing guitar",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janesmith@example.com",
    age: 30,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Designer",
    hobby: "Painting",
  },
  {
    id: 3,
    name: "David Johnson",
    email: "davidjohnson@example.com",
    age: 35,
    city: "Sydney",
    country: "Australia",
    phone: "+61 876-543-2109",
    gender: "Male",
    occupation: "Teacher",
    hobby: "Reading books",
  },
  {
    id: 4,
    name: "Emily Wilson",
    email: "emilywilson@example.com",
    age: 28,
    city: "Toronto",
    country: "Canada",
    phone: "+1 123-456-7890",
    gender: "Female",
    occupation: "Developer",
    hobby: "Playing soccer",
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michaelbrown@example.com",
    age: 32,
    city: "Los Angeles",
    country: "United States",
    phone: "+1 987-654-3210",
    gender: "Male",
    occupation: "Doctor",
    hobby: "Watching movies",
  },
  {
    id: 6,
    name: "Sophia Wilson",
    email: "sophiawilson@example.com",
    age: 29,
    city: "London",
    country: "United Kingdom",
    phone: "+44 123-456-7890",
    gender: "Female",
    occupation: "Writer",
    hobby: "Writing poetry",
  },
  {
    id: 7,
    name: "Daniel Johnson",
    email: "danieljohnson@example.com",
    age: 42,
    city: "New York",
    country: "United States",
    phone: "+1 987-654-3210",
    gender: "Male",
    occupation: "Manager",
    hobby: "Playing chess",
  },
  {
    id: 8,
    name: "Olivia Smith",
    email: "oliviasmith@example.com",
    age: 27,
    city: "Paris",
    country: "France",
    phone: "+33 123-456-7890",
    gender: "Female",
    occupation: "Artist",
    hobby: "Drawing",
  },
  {
    id: 9,
    name: "Alexander Lee",
    email: "alexanderlee@example.com",
    age: 38,
    city: "San Francisco",
    country: "United States",
    phone: "+1 987-654-3210",
    gender: "Male",
    occupation: "Engineer",
    hobby: "Playing basketball",
  },
  {
    id: 10,
    name: "Mia Davis",
    email: "miadavis@example.com",
    age: 31,
    city: "Sydney",
    country: "Australia",
    phone: "+61 123-456-7890",
    gender: "Female",
    occupation: "Architect",
    hobby: "Traveling",
  },
  {
    id: 11,
    name: "William Johnson",
    email: "williamjohnson@example.com",
    age: 45,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Lawyer",
    hobby: "Playing tennis",
  },
  {
    id: 12,
    name: "Charlotte Brown",
    email: "charlottebrown@example.com",
    age: 33,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Teacher",
    hobby: "Gardening",
  },
  {
    id: 13,
    name: "James Miller",
    email: "jamesmiller@example.com",
    age: 36,
    city: "Sydney",
    country: "Australia",
    phone: "+61 123-456-7890",
    gender: "Male",
    occupation: "Doctor",
    hobby: "Playing piano",
  },
  {
    id: 14,
    name: "Amelia Wilson",
    email: "ameliawilson@example.com",
    age: 26,
    city: "Toronto",
    country: "Canada",
    phone: "+1 987-654-3210",
    gender: "Female",
    occupation: "Software Developer",
    hobby: "Coding",
  },
  {
    id: 15,
    name: "Benjamin Johnson",
    email: "benjaminjohnson@example.com",
    age: 39,
    city: "Los Angeles",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Manager",
    hobby: "Playing video games",
  },
  {
    id: 16,
    name: "Lily Taylor",
    email: "lilytaylor@example.com",
    age: 28,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Designer",
    hobby: "Photography",
  },
  {
    id: 17,
    name: "Ethan Davis",
    email: "ethandavis@example.com",
    age: 43,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Engineer",
    hobby: "Playing soccer",
  },
  {
    id: 18,
    name: "Chloe Wilson",
    email: "chloewilson@example.com",
    age: 29,
    city: "Paris",
    country: "France",
    phone: "+33 987-654-3210",
    gender: "Female",
    occupation: "Writer",
    hobby: "Writing novels",
  },
  {
    id: 19,
    name: "Daniel Anderson",
    email: "danielanderson@example.com",
    age: 32,
    city: "San Francisco",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Artist",
    hobby: "PaintSure, here are the remaining user records in the array",
  },
  {
    id: 20,
    name: "Sofia Brown",
    email: "sofiabrown@example.com",
    age: 31,
    city: "Sydney",
    country: "Australia",
    phone: "+61 987-654-3210",
    gender: "Female",
    occupation: "Teacher",
    hobby: "Cooking",
  },
  {
    id: 21,
    name: "Jackson Wilson",
    email: "jacksonwilson@example.com",
    age: 45,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Doctor",
    hobby: "Playing basketball",
  },
  {
    id: 22,
    name: "Harper Johnson",
    email: "harperjohnson@example.com",
    age: 33,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Engineer",
    hobby: "Reading books",
  },
  {
    id: 23,
    name: "Sebastian Davis",
    email: "sebastiandavis@example.com",
    age: 37,
    city: "Sydney",
    country: "Australia",
    phone: "+61 123-456-7890",
    gender: "Male",
    occupation: "Manager",
    hobby: "Playing guitar",
  },
  {
    id: 24,
    name: "Ella Miller",
    email: "ellamiller@example.com",
    age: 27,
    city: "Toronto",
    country: "Canada",
    phone: "+1 987-654-3210",
    gender: "Female",
    occupation: "Designer",
    hobby: "Painting",
  },
  {
    id: 25,
    name: "Aiden Wilson",
    email: "aidenwilson@example.com",
    age: 40,
    city: "Los Angeles",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Teacher",
    hobby: "Photography",
  },
  {
    id: 26,
    name: "Mila Taylor",
    email: "milataylor@example.com",
    age: 29,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Writer",
    hobby: "Writing poetry",
  },
  {
    id: 27,
    name: "Carter Anderson",
    email: "carteranderson@example.com",
    age: 42,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Artist",
    hobby: "Drawing",
  },
  {
    id: 28,
    name: "Scarlett Smith",
    email: "scarlettsmith@example.com",
    age: 28,
    city: "Paris",
    country: "France",
    phone: "+33 987-654-3210",
    gender: "Female",
    occupation: "Engineer",
    hobby: "Playing tennis",
  },
  {
    id: 29,
    name: "Luke Johnson",
    email: "lukejohnson@example.com",
    age: 39,
    city: "San Francisco",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Doctor",
    hobby: "Writing novels",
  },
  {
    id: 30,
    name: "Avery Davis",
    email: "averydavis@example.com",
    age: 30,
    city: "Sydney",
    country: "Australia",
    phone: "+61 987-654-3210",
    gender: "Female",
    occupation: "Teacher",
    hobby: "Traveling",
  },
  {
    id: 31,
    name: "Henry Wilson",
    email: "henrywilson@example.com",
    age: 46,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Manager",
    hobby: "Playing soccer",
  },
  {
    id: 32,
    name: "Evelyn Brown",
    email: "evelynbrown@example.com",
    age: 34,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Designer",
    hobby: "Photography",
  },
  {
    id: 33,
    name: "Owen Davis",
    email: "owendavis@example.com",
    age: 44,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Engineer",
    hobby: "Playing basketball",
  },
  {
    id: 34,
    name: "Zoe Wilson",
    email: "zoewilson@example.com",
    age: 30,
    city: "Paris",
    country: "France",
    phone: "+33 987-654-3210",
    gender: "Female",
    occupation: "Writer",
    hobby: "Painting",
  },
  {
    id: 35,
    name: "Gabriel Anderson",
    email: "gabrielanderson@example.com",
    age: 31,
    city: "San Francisco",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Artist",
    hobby: "Playing guitar",
  },
  {
    id: 36,
    name: "Penelope Johnson",
    email: "penelopejohnson@example.com",
    age: 29,
    city: "Sydney",
    country: "Australia",
    phone: "+61 987-654-3210",
    gender: "Female",
    occupation: "Teacher",
    hobby: "Reading books",
  },
  {
    id: 37,
    name: "Julian Miller",
    email: "julianmiller@example.com",
    age: 35,
    city: "Toronto",
    country: "Canada",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Doctor",
    hobby: "Playing soccer",
  },
  {
    id: 38,
    name: "Eleanor Wilson",
    email: "eleanorwilson@example.com",
    age: 27,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Engineer",
    hobby:
      "Writing poetryCertainly! Here are the remaining user records in the array",
  },
  {
    id: 39,
    name: "Liam Johnson",
    email: "liamjohnson@example.com",
    age: 38,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Manager",
    hobby: "Drawing",
  },
  {
    id: 40,
    name: "Aria Smith",
    email: "ariasmith@example.com",
    age: 28,
    city: "Paris",
    country: "France",
    phone: "+33 987-654-3210",
    gender: "Female",
    occupation: "Designer",
    hobby: "Playing tennis",
  },
  {
    id: 41,
    name: "Henry Davis",
    email: "henrydavis@example.com",
    age: 40,
    city: "San Francisco",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Doctor",
    hobby: "Photography",
  },
  {
    id: 42,
    name: "Ella Wilson",
    email: "ellawilson@example.com",
    age: 29,
    city: "Sydney",
    country: "Australia",
    phone: "+61 987-654-3210",
    gender: "Female",
    occupation: "Writer",
    hobby: "Writing novels",
  },
  {
    id: 43,
    name: "Leo Johnson",
    email: "leojohnson@example.com",
    age: 41,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Engineer",
    hobby: "Playing basketball",
  },
  {
    id: 44,
    name: "Aurora Brown",
    email: "aurorabrown@example.com",
    age: 32,
    city: "London",
    country: "United Kingdom",
    phone: "+44 987-654-3210",
    gender: "Female",
    occupation: "Teacher",
    hobby: "Painting",
  },
  {
    id: 45,
    name: "Sebastian Anderson",
    email: "sebastiananderson@example.com",
    age: 33,
    city: "New York",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Artist",
    hobby: "Playing guitar",
  },
  {
    id: 46,
    name: "Stella Smith",
    email: "stellasmith@example.com",
    age: 27,
    city: "Paris",
    country: "France",
    phone: "+33 987-654-3210",
    gender: "Female",
    occupation: "Engineer",
    hobby: "Reading books",
  },
  {
    id: 47,
    name: "Julian Davis",
    email: "juliandavis@example.com",
    age: 34,
    city: "San Francisco",
    country: "United States",
    phone: "+1 123-456-7890",
    gender: "Male",
    occupation: "Manager",
    hobby: "Writing poetry",
  },
  {
    id: 48,
    name: "Emma Wilson",
    email: "emmawilson@example.com",
    age: 29,
    city: "Toronto",
    country: "Canada",
    phone: "+1 987-654-3210",
    gender: "Female",
    occupation: "Software Developer",
    hobby: "Cooking",
  },
  {
    id: 49,
    name: "Liam Anderson",
    email: "liamanderson@example.com",
    age: 40,
    city: "Berlin",
    country: "Germany",
    phone: "+49 123-456-7890",
    gender: "Male",
    occupation: "Manager",
    hobby: "Photography",
  },
  {
    id: 50,
    name: "Olivia Martinez",
    email: "oliviamartinez@example.com",
    age: 27,
    city: "Barcelona",
    country: "Spain",
    phone: "+34 987-654-3210",
    gender: "Female",
    occupation: "Writer",
    hobby: "Hiking",
  },
];
